// <auto-generated />
using System;
using MiApiORACLE.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace MiApiORACLE.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250428205506_tableConfiguration")]
    partial class tableConfiguration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MiApiORACLE.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CUSTOMER_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"), 1L, 1);

                    b.Property<string>("EmailAdress")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("EMAIL_ADDRESS");

                    b.Property<string>("FullName")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("FULL_NAME");

                    b.HasKey("CustomerId");

                    b.ToTable("CUSTOMERS");
                });

            modelBuilder.Entity("MiApiORACLE.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ORDER_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"), 1L, 1);

                    b.Property<int>("CustomerId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CUSTOMER_ID");

                    b.Property<string>("OrderStatus")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ORDER_STATUS");

                    b.Property<DateTime>("OrderTimestamp")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("ORDER_TMS");

                    b.Property<int>("StoreId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("STORE_ID");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.ToTable("ORDERS");
                });

            modelBuilder.Entity("MiApiORACLE.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ORDER_ID");

                    b.Property<int>("LineItemId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("LINE_ITEM_ID");

                    b.Property<int>("ProductId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PRODUCT_ID");

                    b.Property<int>("Quantity")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("QUANTITY");

                    b.Property<int>("ShipmentId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SHIPMENT_ID");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("UNIT_PRICE");

                    b.HasKey("OrderId", "LineItemId");

                    b.ToTable("ORDERS_ITEMS");
                });

            modelBuilder.Entity("MiApiORACLE.Models.Order", b =>
                {
                    b.HasOne("MiApiORACLE.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("MiApiORACLE.Models.OrderItem", b =>
                {
                    b.HasOne("MiApiORACLE.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("MiApiORACLE.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("MiApiORACLE.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
